language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - COMPOSER_ARGS=""
  - COMPOSER_ARGS="--prefer-lowest"

install:
  - composer update ${COMPOSER_ARGS} --dev --no-interaction

script:
  - phpunit --verbose

sudo: false
